macros/sp_create_prod_clone.sql

force github to take new file

---

models/silver/silver__traces.yml

disable a test in silver traces

disable_traces_test

---

.gitignore
macros/tests/tx_block_count.sql
models/silver/silver__logs.sql
models/silver/silver__logs.yml
models/silver/silver__traces.sql

1. Added tx_gaps test to `silver_logs`
2. Changed unique key to tx_hash in `silver_logs` and `silver_traces`

AN-2584/unique-key-tx-test

---

README.md
dbt_project.yml
macros/tags/add_database_or_schema_tags.sql
macros/tags/snowflake_tagging.sql
models/sushi/sushi__dim_dex_pools.sql
models/sushi/sushi__dim_kashi_pairs.sql
models/sushi/sushi__ez_borrowing.sql
models/sushi/sushi__ez_lending.sql
models/sushi/sushi__ez_swaps.sql

1. Implemented Snowflake tags via Macros and Model configs
2. Set `UPDATE_SNOWFLAKE_TAGS: True` and updated `readme.md` accordingly
3. Need to run `dbt run-operation` after merge
4. [Ticket](https://team-1612274056224.atlassian.net/browse/AN-2699?atlOrigin=eyJpIjoiMjBkNWI3ZTUyN2M4NDI4YzkzNDliYzRiOTZkNzExMGYiLCJwIjoiaiJ9)

AN-2699/snowflake-tags-bsc

---

macros/sp_create_prod_clone.sql

1. Updated `sp_create_prod_clone` with new format/process 
2. Added var to fix issue with snowflake tagging on dev
3. [Ticket](https://team-1612274056224.atlassian.net/browse/AN-2728?atlOrigin=eyJpIjoiYjNiODU0ODFmMDlkNDIxMGI2ZmQ4NTI2MjE5MjkzMjciLCJwIjoiaiJ9)

AN-2728/dev-tag-fix-bsc

---

.github/workflows/dbt_docs_update.yml
.github/workflows/dbt_run_adhoc.yml
.github/workflows/dbt_run_dev_refresh.yml
.github/workflows/dbt_run_incremental.yml
.github/workflows/dbt_test.yml

1. Modified workflows to reference `environment variables` instead of `secrets` for non-sensitive variables
2. [Ticket](https://team-1612274056224.atlassian.net/browse/AN-2756)

AN-2756/env-var-update

---

.github/workflows/dbt_run_api_feeder_table.yml
models/bronze/api_udf/bronze_api__contract_abis.sql
models/bronze/api_udf/bronze_api__contract_abis.yml
models/bronze/api_udf/bronze_api__token_reads.sql
models/bronze/api_udf/bronze_api__token_reads.yml
models/silver/API_udf/silver__relevant_abi_contracts.sql
models/silver/API_udf/silver__relevant_abi_contracts.yml
models/silver/API_udf/silver__relevant_contracts.sql
models/silver/API_udf/silver__relevant_contracts.yml
models/silver/abis/silver__proxies.sql
models/silver/abis/silver__proxies.yml
models/sources.yml

- adds pipeline for contract name, symbol, and decimal reads (dim_contracts)
- adds pipeline for ABIs for use in decoding

An 2771/api pipelines

---

models/sushi/sushi__dim_kashi_pairs.yml
models/sushi/sushi__ez_borrowing.yml
models/sushi/sushi__ez_lending.yml

1. Added `Deprecating soon` to core sushi model descriptions
2. Removed tests from applicable yml files

AN-2785/sushi-tests-bsc

---

models/gold/core__ez_token_transfers.sql

Joined contracts to ez_token_transfers for improved decimals and symbols coverage

AN-3020/add-contracts

---

.github/workflows/dbt_run_incremental.yml
.github/workflows/dbt_run_temp_backfill.yml
macros/dbt/get_merge_sql.sql
macros/dbt/get_tmp_relation_type.sql
macros/lookback.sql
models/silver/core/silver__blocks2.sql
models/silver/core/silver__logs2.sql
models/silver/core/silver__receipts.sql
models/silver/core/silver__traces2.sql
models/silver/core/silver__transactions2.sql

- adds streamline core models
- adds job to fill new models 500k blocks / 2 hours 
- removes new models from regular incremental
- moves history job to adhoc

core models

---

models/bronze/decoder/bronze__decoded_logs.sql
models/bronze/decoder/bronze__fr_decoded_logs.sql
models/silver/silver__decoded_logs.sql
models/silver/streamline/decoder/streamline__complete_decode_logs.sql

- adds a bronze layer for complete and `silver__decoded_logs`
- updates unique key to match `silver__logs2`
- removes lookback

add bronze and key update

---

models/silver/core/silver__confirmed_blocks.sql

uses full file history to backfill

use complete  source

---

.github/workflows/dbt_test_daily.yml
.github/workflows/dbt_test_intraday.yml
.github/workflows/dbt_test_monthly.yml

- Update environment name
- Create monthly test yml

An 3575/full-test-updates

---

models/silver/dex/hashflow/silver_dex__hashflow_v3_pools.sql
models/silver/dex/hashflow/silver_dex__hashflow_v3_pools.yml
models/silver/dex/hashflow/silver_dex__hashflow_v3_swaps.sql
models/silver/dex/hashflow/silver_dex__hashflow_v3_swaps.yml
models/silver/dex/silver_dex__complete_dex_swaps.sql

`dbt run -m models/silver/dex/hashflow/silver_dex__hashflow_v3_pools.sql models/silver/dex/hashflow/silver_dex__hashflow_v3_swaps.sql models/silver/dex/silver_dex__complete_dex_swaps.sql models/gold/defi/defi__ez_dex_swaps.sql --full-refresh`

AN-4087/Add-Hashflow-V3-swaps-and-pools 

---

models/silver/core/tests/transfers/test_silver__transfers_full.sql
models/silver/core/tests/transfers/test_silver__transfers_full.yml
models/silver/core/tests/transfers/test_silver__transfers_recent.sql
models/silver/core/tests/transfers/test_silver__transfers_recent.yml

Moved transfers to core recent/full test structure

AN-4129/fix-long-running-daily-tests

---

models/silver/core/silver__contracts.sql
models/silver/nft/silver__complete_nft_sales.sql
models/silver/nft/silver__nft_transfers.sql

Change heal logic for nft models

Transfers fill

---

packages.yml

`dbt run -m models/github_actions`

package update

---

models/silver/defi/lending/kinza/silver__kinza_tokens.sql
models/silver/defi/lending/kinza/silver__kinza_tokens.yml
models/silver/defi/lending/radiant/silver__radiant_tokens.sql
models/silver/defi/lending/radiant/silver__radiant_tokens.yml

`dbt run -m models/silver/defi/lending/kinza/silver__kinza_tokens.sql models/silver/defi/lending/radiant/silver__radiant_tokens.sql --full-refresh`

AN-4556/add-aave-token-model-tests 

---

models/bronze/api_udf/bronze_api__contract_abis.sql
models/bronze/api_udf/bronze_api__token_reads.sql
models/silver/defi/bridge/stargate/silver_bridge__stargate_createpool.sql
models/sources.yml
package-lock.yml
packages.yml

`dbt run -s livequery_models.deploy.core --vars '{DROP_UDFS_AND_SPS: true}' -t prod && dbt run -s livequery_models.deploy.core --vars '{UPDATE_UDFS_AND_SPS: true}' -t prod`

vault secrets

---

models/streamline/silver/core/complete/streamline__complete_receipts.sql

collect filenames

---

models/silver/defi/lending/radiant/silver__radiant_tokens.sql

`dbt run -m models/silver/defi/lending/radiant/silver__radiant_tokens.sql models/silver/defi/lending/radiant/silver__radiant_borrows.sql --full-refresh -t dev-2xl && dbt run --vars '{"HEAL_CURATED_MODEL":"radiant"}' -m models/silver/defi/lending/complete_lending/silver__complete_lending_borrows.sql+`

AN-4748/radiant-borrows-missing-amounts 

---

models/doc_descriptions/transfers/bsc_transfer_table_doc.md
models/doc_descriptions/transfers/evm_transfers_table_doc.md
models/gold/core/core__ez_native_transfers.yml
models/gold/core/core__ez_token_transfers.yml
models/gold/core/core__fact_token_transfers.yml

to capture docs updates in snowflake: `dbt run -m models/gold/core/core__ez_native_transfers.sql models/gold/core/core__ez_token_transfers.sql models/gold/core/core__fact_token_transfers.sql`

AN-4879/transfers-docs

---

models/gold/nft/nft__ez_nft_sales.yml
models/silver/nft/sales/silver__complete_nft_sales.sql
models/silver/nft/sales/silver__element_sales.sql
models/silver/nft/sales/silver__element_sales.yml
models/silver/nft/sales/silver__pancakeswap_collection_details.sql
models/silver/nft/sales/silver__pancakeswap_sales.sql
models/silver/nft/sales/silver__seaport_1_1_sales.sql
models/silver/nft/sales/silver__seaport_1_4_sales.sql
models/silver/nft/sales/silver__seaport_1_5_sales.sql
models/silver/nft/sales/silver__seaport_1_6_sales.sql
models/silver/nft/sales/silver__tofunft_sales.sql

Add element marketplace to BSC
`dbt run -m models/silver/nft/sales/silver__element_sales.sql --full-refresh && dbt run -m models/silver/nft/sales/silver__complete_nft_sales.sql --vars '{"HEAL_MODELS":["element"]}'`

An 4750/element bsc

---

.github/workflows/dbt_run_reload_traces.yml
dbt_project.yml
models/silver/core/silver__fact_traces2.sql

`dbt run -m models/silver/core/silver__fact_traces2.sql --full-refresh`

An 4958/gold traces2

---

models/silver/defi/lending/kinza/silver__kinza_deposits.sql

`delete from BSC.silver.complete_lending_deposits where tx_hash = '0xa0d50d81a22b54f3ef6aa1a1bfb27ccbbc6795fbdb2d88df9aa9c3797a96f2cf';`
`delete from bsc.silver.KINZA_DEPOSITS where tx_hash = '0xa0d50d81a22b54f3ef6aa1a1bfb27ccbbc6795fbdb2d88df9aa9c3797a96f2cf';`

AN-5229/kinza-lending-failures

---

.github/workflows/dbt_run_traces_fix.yml
models/silver/core/silver__fact_traces2.sql
models/silver/core/traces2_fix/silver__fact_traces2_fix.sql

add traces2 fix and workflow 
`dbt run -m models/silver/core/traces2_fix/silver__fact_traces2_fix.sql --full-refresh`

AN-5669/traces2-fix-bsc

---

models/silver/defi/lending/venus/silver__venus_asset_details.sql

`dbt run -m models/silver/defi/lending/venus/silver__venus_asset_details.sql models/silver/defi/lending/venus/silver__venus_liquidations.sql --full-refresh && dbt run --vars '{"HEAL_MODELS":"venus"}' -m models/silver/defi/lending/complete_lending/silver__complete_lending_liquidations.sql`

venus-asset-details-fix

---

models/silver/defi/lending/venus/silver__venus_asset_details.sql

`dbt run -m models/silver/defi/lending/venus --full-refresh &&  dbt run --vars '{"HEAL_MODELS":"venus"}' -m models/silver/defi/lending/complete_lending`

add-native-to-venus 

---

models/doc_descriptions/fsc_evm/evm_deprecations.md
models/gold/nft/nft__ez_nft_sales.sql
models/gold/nft/nft__ez_nft_sales.yml
models/gold/nft/nft__ez_nft_transfers.sql
models/gold/nft/nft__ez_nft_transfers.yml

`dbt run -m models/gold/nft/nft__ez_nft_sales.sql models/gold/nft/nft__ez_nft_transfers.sql --full-refresh`

Add nft columns

---

models/silver/defi/dex/pancake_swap/silver_dex__pancakeswap_v3_swaps.sql

fix `token_in` and `token_out` logic.
dbt run -m models/silver/defi/dex/pancake_swap/silver_dex__pancakeswap_v3_swaps.sql --full-refresh && dbt run -m models/silver/defi/dex/silver_dex__complete_dex_swaps.sql --vars '{"HEAL_MODELS":"pancakeswap_v3"}'

pcsv3-swap-fix

---

models/silver/defi/bridge/across/silver_bridge__across_v3fundsdeposited.sql
models/silver/defi/bridge/across/silver_bridge__across_v3fundsdeposited.yml
models/silver/defi/bridge/silver_bridge__complete_bridge_activity.sql

Add Across bridge
`dbt run -m models/silver/defi/bridge/across/silver_bridge__across_v3fundsdeposited.sql --full-refresh && dbt run -m models/silver/defi/bridge/silver_bridge__complete_bridge_activity.sql --vars '{"HEAL_MODELS": ["across_v3"]}'`

AN-6385/add across bridge
